### ISSUE TITLE
Is it possible to broadcast a WS response from a HTTPS endpoint?🤔 

### ISSUE THREAD

**Issue by maverickVision** [gofiber/recipes#57]
Hello everyone, I'm starting with websockets and I would like to know if it is possible to send a WS notification after some action is done inside a HTTPS endpoint. For example, I want to notify some users (I still need to figure out how to broadcast just to some users) when a new User is created on the admin panel. A POST request is made to the endpoint /agent and I would like to use websockets to send this new data and populate a data grid when a certain user is on the Agents creation screen.

I don't know if its clear, but is it possible to be made?

Thanks in advance.

**Comment by WLun001** [comment]
Hi @maverickVision, I think you need separate websocket for that. And your API server connects to your websocket


```go
app.Get("/operation", func (c *fiber.Ctx) error {

ws.send('message')

return c.SendString("done!")
})
```

**Comment by maverickVision** [comment]
Hi @WLun001, I've created this simple repo with the minimal working structure using fiber and it's websockets plugin, could you help me modify it to get it working?

https://github.com/maverickVision/testws

**Comment by WLun001** [comment]
@maverickVision I am not free at the moment, maybe you could take a look at [this repo](https://github.com/WLun001/scaling-ws/tree/problem) that address the same issue. 

Check on `problem` branch.

**Comment by maverickVision** [comment]
Thanks @WLun001, I'll take a look. But I already saw that you are using the gin framework. Since I'm still beggining with Go, do you think it's better to learn gin instead of fiber?

**Comment by Fenny** [comment]
I'm not sure if I fully understand the question, but are trying to run a websocket server with TLS?

**Comment by WLun001** [comment]
> Thanks @WLun001, I'll take a look. But I already saw that you are using the gin framework. Since I'm still beggining with Go, do you think it's better to learn gin instead of fiber?

@maverickVision If you coming from Express, Fiber would be good choice, it has familiar APIs. Any framework will do, or without framework. That's my personal opinion.

**Comment by maverickVision** [comment]
> @maverickVision I am not free at the moment, maybe you could take a look at [this repo](https://github.com/WLun001/scaling-ws/tree/problem) that address the same issue.
> 
> Checkout on `problem` branch.

@WLun001 I'm following your code from this repo, on the solution brach. The problem with fiber is that I can't access the responseWriter from fiber Context, in order to upgrade the connection inside the ServeWs method... and according to this issue [#721](https://github.com/gofiber/fiber/issues/721), it is really not possible. I guess I will need to rewrite my project with Gin just because of this issue.

**Comment by WLun001** [comment]
@maverickVision You don't need to access to responseWriter. You could use https://github.com/gofiber/websocket.

**Comment by maverickVision** [comment]
> @maverickVision You don't need to access to responseWriter. You could use https://github.com/gofiber/websocket.

I've made the following changes:

**main.go**
```
app.Get("/ws", websocket.New(func(c *websocket.Conn) {
		ws.ServeWs(hub, c, nc, subject)
	}))
```

**ws.go**
```
func ServeWs(hub *Hub, conn *websocket.Conn, nc *nats.Conn, subject string) {
	client := &Client{hub: hub, conn: conn, send: make(chan []byte, 256)}

	// subscribe nats
	sub, err := nc.Subscribe(subject, func(m *nats.Msg) {
		log.Println(string(m.Data))
		client.hub.broadcast <- m.Data
	})
	if err != nil {
		log.Fatal(err)
	}
	nc.Flush()

	if err := nc.LastError(); err != nil {
		log.Fatal(err)
	}

	client.natsSub = sub
	client.hub.register <- client

	// Allow Connection of memory referenced by the calloer by doing all work in new goroutines
	go client.writePump()
	go client.readPump()
}
```

I've switched the conn variable from the upgraded gin context to fiber websocket conn. All services gone up without issues (using the same commands you use in your code), but when I open a browser tab on localhost:8080, I get the following error on the `make start-api` console log:

```
2020/10/12 13:53:44 ws.go:64: Current connected ws client: 1
2020/10/12 13:53:44 ws.go:71: Unsubscribe
2020/10/12 13:53:44 ws.go:74: Current connected ws client: 0
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x149e03e]

goroutine 8 [running]:
github.com/fasthttp/websocket.(*Conn).Close(...)
	/Users/marcelo/go/pkg/mod/github.com/fasthttp/websocket@v1.4.3-beta.2/conn.go:344
github.com/maverickvision/testws/internal/ws.(*Client).writePump.func1(0xc00007e320, 0xc00028a0a0)
	/Users/marcelo/playground/golang/testws/internal/ws/ws.go:160 +0x3e
panic(0x150bc00, 0x1a06520)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/fasthttp/websocket.(*Conn).SetWriteDeadline(...)
	/Users/marcelo/go/pkg/mod/github.com/fasthttp/websocket@v1.4.3-beta.2/conn.go:781
github.com/maverickvision/testws/internal/ws.(*Client).writePump(0xc00028a0a0)
	/Users/marcelo/playground/golang/testws/internal/ws/ws.go:166 +0x311
created by github.com/maverickvision/testws/internal/ws.ServeWs
	/Users/marcelo/playground/golang/testws/internal/ws/ws.go:221 +0x240
```

I printed the `conn` and `client` variables on **ws.go**, and they are not null, what could it be?

I've updated my repo with the [latest code](https://github.com/maverickVision/testws), if you can help.

**Comment by Fenny** [comment]
Closing due to inactivity, feel free to re-open.
